name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python online_runner.py
