name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          cd /home/runner/work/ETE-reactNative/ETE-reactNative/pythonProject/
          python online_runner.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: /home/runner/work/ETE-reactNative/ETE-reactNative/pythonProject/output.txt

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: output
          path: artifacts
          
      - name: Move output.txt to project directory
        run: mv artifacts/output.txt /home/runner/work/ETE-reactNative/ETE-reactNative/pythonProject/output.txt
        
      - name: Configure Git
        run: |
          git config --global user.email "rabkeb@post.bgu.ac.il"
          git config --global user.name "Barak"
      - name: Commit changes
        run: |
          git add /home/runner/work/ETE-reactNative/ETE-reactNative/pythonProject/output.txt
          git commit -m "Add output.txt from script run"
          
      - name: Push changes
        run: |
          git push origin HEAD:main
