name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Change to pythonProject directory
        run: ls /home/runner/work
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run script
        run: |
          python online_runner.py
