name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run script
        run: |
          cd /home/runner/work/ETE-reactNative/ETE-reactNative/pythonProject/
          python online_runner.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: /home/runner/work/ETE-reactNative/ETE-reactNative/pythonProject/output.txt

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: output
          path: artifacts
          
      - name: Move output.txt to project directory
        run: mv artifacts/output.txt pythonProject/output.txt
            ls /pythonProject
        
      - name: Configure Git
        run: |
          git config --global user.email "omrigo13@gmail.com"
          git config --global user.name "Omri Goldberg"
      - name: Commit changes
        run: |
          git add ETE-reactNative/pythonProject/output.txt
          git commit -m "Add output.txt from script run"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
